### ISSUE TITLE
time.Time has no field or method Compar

### ISSUE THREAD

**Issue by fahdmirza** [perk11/large-model-proxy#1]
Hi,
 Hi,
 Hi, getting following error:

Ubuntu@0136-ict-prxmx50056:~/large-model-proxy$ go build -o largemodelproxy main.go
# command-line-arguments
./main.go:281:67: resourceManager.runningServices[requestingService].lastUsed.Compare undefined (type time.Time has no field or method Compare)
Ubuntu@0136-ict-prxmx50056:~/large-model-proxy$ go version
go version go1.19.1 linux/amd64

Ubuntu@0136-ict-prxmx50056:~/large-model-proxy$ cat /etc/*release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04

**Comment by fahdmirza** [comment]
Its ok, I was able to resolve it by upgrading my go version. I also did a local installation video of it:  https://youtu.be/7iDda0xAYlk

Thanks.

**Comment by perk11** [comment]
Thanks, I will replace this function to be compatible with go 1.19 and will provide binaries for Ubuntu
