### ISSUE TITLE
Feature Request: Automatically kill the process after a configurable amount of time

### ISSUE THREAD

**Issue by jukofyork** [perk11/large-model-proxy#3]
It would be helpful to automatically unload the models / kill the process after a configurable amount of time so as to reduce the power draw that some cards suffer from when VRAM is populated.

**Comment by perk11** [comment]
This will be implemented.

**Comment by perk11** [comment]
@jukofyork This feature has been added in 7d0b9d1b9cc72e6b9681fb45378ce3dc1952d7e8

There is a new setting "ShutDownAfterInactivitySeconds", both on the global level and service level.

**Comment by jukofyork** [comment]
Thanks!
